cd /dE:\CaseCode\Codes\SynologyDrive\MCU_FW_DL_ODM_Code\MCU_FW_DL_ODM\MCU_FW_DL_ODM\MCU_FW_DL_ODM_V1.0.0\CCSLOAD
ccsload.exe DEVICE=PIC18F46K22 AREAS=PDC WRITE="E:\CaseCode\Codes\SynologyDrive\MCU_FW_DL_ODM_Code\MCU_FW_DL_ODM\MCU_FW_DL_ODM\MCU_FW_DL_ODM_V1.0.0\QDE016\1.0.2L-bldr.hex" +RUN
echo %ERRORLEVEL% >E:\CaseCode\Codes\SynologyDrive\MCU_FW_DL_ODM_Code\MCU_FW_DL_ODM\MCU_FW_DL_ODM\MCU_FW_DL_ODM_V1.0.0\CCSLOAD\CCSLOAD_LOG.txt
